name: Scaffold-Better
version: '1.0-SNAPSHOT'
main: me.saimon527.scaffoldenhanced.ScaffoldEnhanced
api-version: '1.20'
authors: [Saimon527]
description: Upgraded version of scaffold
commands:
  scaffold:
    description: Enables or disables scaffold.
